CREATE TABLE IF NOT EXISTS welldiary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    field_name TEXT NOT NULL,
    long_well_name TEXT NOT NULL DEFAULT '',
    drilled DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
